/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_927333_3_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_927333_1[] = { "downSit", "freeFall", "runFall", "runSit", "walkFall", "walkSit" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_927333_2_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_927333_2_axes_size = 3;
ei_dsp_config_spectral_analysis_t ei_dsp_config_927333_2 = {
    2, // uint32_t blockId
    4, // int implementationVersion
    3, // int length of axes
    0.08248086991542f, // float scale-axes
    1, // int input-decimation-ratio
    "high", // select filter-type
    0.9765625f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    32, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "rbio3.3", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_927333_2[63] = { 0.027610768997607633, -0.030296106126256647, 0.7045940398888002, 2.2471808340999804, 4.7516569965995545, -3.345096116221771, -2.8369238675742303, -3.101187471181378, -3.3659858294559286, -3.554618404398771, -3.722007343350493, -3.843472672901802, -3.954444827214665, -4.00907583962265, -4.1320118057317865, -4.196676338622589, -4.291364971951134, -4.343004315928586, -4.400023529996094, -4.425021046141663, -4.473273599339064, 0.02662826751706225, 0.10051401907875228, 0.8909349209968291, 2.18280887525331, 4.48547303205624, -3.3273659162447062, -2.816394475104033, -3.0946721921377525, -3.325476700284611, -3.488611027774244, -3.6334060567655344, -3.768875408378835, -3.8840266144494002, -3.9607253495470567, -4.109774306768681, -4.184781819328207, -4.27773801010793, -4.326180129676088, -4.381957407759047, -4.395759640280955, -4.4462850223134245, 0.02317366534203894, -0.04537929041173014, 0.9116029934400007, 2.0205349427060093, 3.8354238798419753, -3.5345509169138687, -3.037505383403398, -3.244954177474154, -3.4048597737231465, -3.56460506718974, -3.6552116263934624, -3.7849910348718794, -3.91488163214738, -4.031300554644088, -4.15035337708351, -4.251101128450017, -4.356608200398788, -4.4312780178915725, -4.507684916315737, -4.527933237571806, -4.574395814693207 };
const float ei_dn_standard_scaler_scale_927333_2[63] = { 27.147537280899723, 1.8623580396130364, 0.35824972656671994, 1.1727654496903055, 0.28164554557904325, 1.2101337086808248, 1.189804258567229, 1.0359035317863328, 1.0220550931003163, 1.0931112421994678, 1.0719380249798707, 1.0389716536277658, 1.0634859002538557, 1.0549097096641529, 1.0242036713973277, 1.027845137011399, 1.0184606336090407, 1.020384492187857, 1.0200572761639801, 1.0159943624593966, 0.9844005961199463, 26.118824713092355, 1.8239710553384452, 0.361071035092945, 1.1721654375513075, 0.27541749844535557, 1.1739464255351386, 1.1406383956574628, 1.1078072122426201, 1.1169609254873962, 1.1932195849156197, 1.2076949303177034, 1.1546217864020496, 1.1658486128952665, 1.1524032883309385, 1.1223084143779538, 1.125705636841943, 1.132641550062943, 1.1258012993588966, 1.113063969933202, 1.1014953871674142, 1.0682303672075584, 28.41002805035651, 1.7688733282438622, 0.3580324242421831, 1.1990604365741349, 0.29410244333664115, 1.358406117601991, 1.3980174074140774, 1.1414754818056614, 1.1408710696050965, 1.2964709241389516, 1.275728937228304, 1.1747830027919042, 1.1953842619403925, 1.1845062563628477, 1.1275398290428598, 1.090526767800064, 1.0660429958192528, 1.0460066170748223, 1.0334230104655413, 1.0224093037088915, 0.9850864270270596 };
const float ei_dn_standard_scaler_var_927333_2[63] = { 0.0013568727592203557, 0.28831925282338805, 7.791628990433228, 0.7270724254359822, 12.606491231836744, 0.6828625302529624, 0.7063971883237324, 0.9318829643339165, 0.9573073349433602, 0.8368955878957047, 0.8702832923754503, 0.926387320814914, 0.8841715311565644, 0.8986062204258156, 0.9532950620190538, 0.9465523304255687, 0.9640765207088651, 0.9604445596079644, 0.9610608451123819, 0.9687626883382028, 1.0319443176077525, 0.0014658608246641577, 0.30058279299969864, 7.6703414638254825, 0.7278169686930751, 13.18308163010289, 0.7256103091843707, 0.7686064540656576, 0.8148386555172416, 0.8015378567803568, 0.7023591651014376, 0.685623213929054, 0.7501023122858967, 0.735725280689529, 0.7529931445743333, 0.7939178417892978, 0.7891332059493783, 0.7794980288956936, 0.7889991018913767, 0.8071602207073899, 0.824203841705354, 0.8763350063419424, 0.0012389582586965018, 0.3195998250834451, 7.801089881622739, 0.6955331806172048, 11.561195226869192, 0.5419269418841286, 0.5116521953263343, 0.7674795723838291, 0.7682929804988974, 0.5949417373574837, 0.6144452434494062, 0.7245772453009095, 0.6998177159697344, 0.7127303984074852, 0.786567895777519, 0.8408670598313664, 0.8799349299883538, 0.9139683068059922, 0.9363619235734258, 0.956644137387554, 1.0305079097575642 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_927333_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_927333_2,
    .mean_data_len = 63,
    .scale_data = (float *)ei_dn_standard_scaler_scale_927333_2,
    .scale_data_len = 63,
    .var_data = (float *)ei_dn_standard_scaler_var_927333_2,
    .var_data_len = 63
};
ei_data_normalization_t ei_data_normalization_config_927333_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_927333_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_927333_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_927333_1[ei_dsp_blocks_927333_1_size] = {
    { // DSP block 2
        2,
        63, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_927333_2, // pointer to config struct
        ei_dsp_config_927333_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_927333_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_927333_2, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_927333_3 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_927333_3_init,
    .model_invoke = &tflite_learn_927333_3_invoke,
    .model_reset = &tflite_learn_927333_3_reset,
    .model_input = &tflite_learn_927333_3_input,
    .model_output = &tflite_learn_927333_3_output,
};

const uint8_t ei_output_tensors_indices_927333_3[1] = { 0 };
const uint8_t ei_output_tensors_size_927333_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_927333_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_927333_3,
    .output_tensors_size = ei_output_tensors_size_927333_3,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_927333_3,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_927333_1_size = 1;
const uint32_t ei_learning_block_927333_3_inputs[1] = { 2 };
const uint8_t ei_learning_block_927333_3_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_927333_1[ei_learning_blocks_927333_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_927333_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_927333_3_inputs,
        ei_learning_block_927333_3_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_927333_3 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_927333_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_927333_1[ei_postprocessing_blocks_927333_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_927333_3,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_927333_1_size = 0;

uint32_t *freeform_outputs_927333_1 = nullptr;

const ei_impulse_t impulse_927333_1 = {
    .project_id = 927333,
    .project_owner = "ThanhTan",
    .project_name = "Fall_Detection",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 63,
    .raw_sample_count = 50,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 50 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 40,
    .frequency = 25,

    .dsp_blocks_size = ei_dsp_blocks_927333_1_size,
    .dsp_blocks = ei_dsp_blocks_927333_1,

    .learning_blocks_size = ei_learning_blocks_927333_1_size,
    .learning_blocks = ei_learning_blocks_927333_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_927333_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_927333_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "AccelerationX + AccelerationY + AccelerationZ",
    .slice_size = (50/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 6,
    .categories = ei_classifier_inferencing_categories_927333_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_927333_1_size,
    .freeform_outputs = freeform_outputs_927333_1
};

ei_impulse_handle_t impulse_handle_927333_1 = ei_impulse_handle_t( &impulse_927333_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_927333_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_927333_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_927333_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_927333_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
