/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_928099_3_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_928099_1[] = { "Fall", "normal" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_928099_2_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_928099_2_axes_size = 3;
ei_dsp_config_spectral_analysis_t ei_dsp_config_928099_2 = {
    2, // uint32_t blockId
    4, // int implementationVersion
    3, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "none", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    32, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_928099_2[63] = { 0.2142389705516577, -0.3179557998598331, 2.761982274570594, 1.7714733129201068, 2.815731391610188, -1.6195563203718615, -1.9504573496835804, -2.1206644828939756, -2.2088209612426373, -2.2502857090465764, -2.3044251183816034, -2.3657775442096063, -2.413292750458006, -2.4851728113901475, -2.6016510273349813, -2.6385829858521683, -2.6821275466046113, -2.698675064366056, -2.7691475053946686, -2.804924087875282, -2.8784890610736626, 0.20680509805982797, 0.12684519888306311, 3.531953702741213, 1.7215237057181751, 2.6418281629351745, -1.6883108852887387, -2.072802565464527, -2.1885589160105714, -2.2728293546837155, -2.3271862542571133, -2.3343151257215187, -2.3821788222059355, -2.4933396616754617, -2.5185910910845566, -2.6020377117296696, -2.6365518487312554, -2.6731809361770145, -2.700863297660059, -2.765817096673796, -2.799170277854547, -2.829611712489347, 0.20143494286681884, -0.0538340898459025, 2.466759179716927, 2.0277479359378607, 3.7652907139854506, -1.347136568197479, -1.8701019129975431, -2.059756526857301, -2.2031338840153896, -2.286547306511137, -2.2902263157915064, -2.3570692413839143, -2.4520776321858757, -2.508959061518395, -2.5534150481403035, -2.5932860134169955, -2.6671714979337335, -2.684366316465426, -2.715628822915192, -2.719636185537568, -2.821715217466691 };
const float ei_dn_standard_scaler_scale_928099_2[63] = { 3.0184966593635467, 0.6687824403262288, 0.14410341318373684, 1.1692583414148219, 0.3455258034094977, 0.6200523282399314, 0.6439184411495905, 0.6621999472837412, 0.6725711536695849, 0.6974564886066699, 0.7446038934531535, 0.7419582285976893, 0.7236172062138887, 0.726696287111475, 0.7471729740174106, 0.7765685347264012, 0.7499149930761417, 0.7862171097818517, 0.76147695911594, 0.7376259823292244, 0.7181255419032252, 3.096510141228954, 0.581815190153723, 0.11307284190680962, 1.1625910597138456, 0.3545675917496079, 0.6070548309211169, 0.6475920683203392, 0.6654891573474744, 0.6654191820766986, 0.6877539455307652, 0.7204782571279948, 0.6996491503268172, 0.7204021431486215, 0.7248396994841723, 0.721352519064193, 0.7218717377924863, 0.7370838495016665, 0.7463046649428104, 0.7357724444259564, 0.7241893587442325, 0.6903996648249889, 3.6421370143394256, 0.679404690290724, 0.14493707681207582, 1.154665921751375, 0.33543958875304253, 0.7552296713592161, 0.7548378867203386, 0.7365766179036091, 0.7219253928365476, 0.7000016118784266, 0.7269578518814309, 0.7172754514324649, 0.7198893745521913, 0.7139977148126462, 0.7172795010289998, 0.7323760459009137, 0.7236558881411056, 0.7498145172581643, 0.7160719173096616, 0.7078762883083398, 0.7075472973820831 };
const float ei_dn_standard_scaler_var_928099_2[63] = { 0.10975355617281175, 2.235786228061568, 48.15611745308054, 0.7314405719528397, 8.376045524115497, 2.601017743480487, 2.411783246401755, 2.280456100304704, 2.2106680099012452, 2.0557285246126398, 1.8036380738773676, 1.8165237844995668, 1.9097751148973388, 1.893625605466528, 1.7912561343912923, 1.6582134011657115, 1.7781808420901777, 1.617763447184838, 1.7245923930514868, 1.8379241652905445, 1.9390957410340401, 0.10429295832627054, 2.9541319422615575, 78.21379968990091, 0.7398540272638238, 7.954299234330376, 2.713589567246918, 2.3844979764300125, 2.2579692955029995, 2.258444215147137, 2.114140368349996, 1.9264522192799625, 2.042863636301037, 1.9268593188200147, 1.9033386064664384, 1.921785421332216, 1.9190218607766734, 1.840628784191517, 1.79542673346542, 1.847195926185464, 1.906758635825552, 2.0979679835282896, 0.07538543424093641, 2.1664213080951766, 47.603732285995804, 0.7500449703409321, 8.887331219948697, 1.7532421850790136, 1.755062633225768, 1.84316469564962, 1.9187366197331563, 2.0408069278550487, 1.8922631698390056, 1.9436947653723093, 1.929605254141186, 1.9615814975318662, 1.9436728181192342, 1.8643684183203701, 1.909570952093442, 1.778657429675743, 1.9502339657052707, 1.9956541057662693, 1.9975103908087564 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_928099_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_928099_2,
    .mean_data_len = 63,
    .scale_data = (float *)ei_dn_standard_scaler_scale_928099_2,
    .scale_data_len = 63,
    .var_data = (float *)ei_dn_standard_scaler_var_928099_2,
    .var_data_len = 63
};
ei_data_normalization_t ei_data_normalization_config_928099_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_928099_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_928099_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_928099_1[ei_dsp_blocks_928099_1_size] = {
    { // DSP block 2
        2,
        63, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_928099_2, // pointer to config struct
        ei_dsp_config_928099_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_928099_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_928099_2, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_928099_3 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_928099_3_init,
    .model_invoke = &tflite_learn_928099_3_invoke,
    .model_reset = &tflite_learn_928099_3_reset,
    .model_input = &tflite_learn_928099_3_input,
    .model_output = &tflite_learn_928099_3_output,
};

const uint8_t ei_output_tensors_indices_928099_3[1] = { 0 };
const uint8_t ei_output_tensors_size_928099_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_928099_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_928099_3,
    .output_tensors_size = ei_output_tensors_size_928099_3,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_928099_3,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_928099_1_size = 1;
const uint32_t ei_learning_block_928099_3_inputs[1] = { 2 };
const uint8_t ei_learning_block_928099_3_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_928099_1[ei_learning_blocks_928099_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_928099_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_928099_3_inputs,
        ei_learning_block_928099_3_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_928099_3 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_928099_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_928099_1[ei_postprocessing_blocks_928099_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_928099_3,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_928099_1_size = 0;

uint32_t *freeform_outputs_928099_1 = nullptr;

const ei_impulse_t impulse_928099_1 = {
    .project_id = 928099,
    .project_owner = "ThanhTan",
    .project_name = "Fall_Detection",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 63,
    .raw_sample_count = 50,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 50 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 40,
    .frequency = 25,

    .dsp_blocks_size = ei_dsp_blocks_928099_1_size,
    .dsp_blocks = ei_dsp_blocks_928099_1,

    .learning_blocks_size = ei_learning_blocks_928099_1_size,
    .learning_blocks = ei_learning_blocks_928099_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_928099_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_928099_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "AccelerationX + AccelerationY + AccelerationZ",
    .slice_size = (50/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 2,
    .categories = ei_classifier_inferencing_categories_928099_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_928099_1_size,
    .freeform_outputs = freeform_outputs_928099_1
};

ei_impulse_handle_t impulse_handle_928099_1 = ei_impulse_handle_t( &impulse_928099_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_928099_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_928099_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_928099_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_928099_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
