; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_eol = CRLF        ; Đây là dòng "thần thánh" giúp gửi lệnh AT thành công. Tự động thêm \r\n (Carriage Return + Line Feed) mỗi khi bạn nhấn Enter gửi lệnh. Tương đương với chế độ "Both NL & CR" trong Arduino IDE.
