/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 25.03.2026 08:05:34

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1552;
#else
constexpr int kTensorArenaSize = 528;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,189 } };
const TfArray<1, float> quant0_scale = { 1, { 0.045605789870023727, } };
const TfArray<1, int> quant0_zero = { 1, { -8 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[2] = { -82, 82, };
const TfArray<1, int> tensor_dimension1 = { 1, { 2 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00032581863342784345, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[2*10] = { 
  33, -102, 65, 102, 108, -92, -4, -111, 34, 97, 
  82, 31, -24, -34, -86, 27, -127, 69, -103, 4, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 2,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0068826344795525074, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 456, 205, -24, -96, -74, 172, 292, 180, 240, 110, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00025155351613648236, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  8, 0, -75, 69, 67, 3, 127, -106, 47, -20, -13, 32, 86, 126, 0, -37, 58, -75, -28, 54, 
  -71, -95, 67, 92, 19, -25, -43, -93, -50, 32, -37, -37, 68, 42, 56, 75, -19, 22, -29, -26, 
  6, -96, -14, 80, -24, -47, -40, 34, -51, -15, 40, 46, -33, -101, 9, -64, 62, -69, -70, -48, 
  58, -12, 90, -9, -38, 74, -58, -34, -42, 58, 88, 46, -65, -91, 12, -39, -29, -22, 87, 70, 
  -39, 42, -90, -47, -78, 67, -43, 17, -80, 51, 78, 56, -18, 30, 27, -79, -44, 101, 58, 44, 
  -69, 99, -62, 58, -21, -96, 9, 66, -92, -55, 52, 45, -58, 82, -39, -63, -2, 39, -66, 27, 
  91, 23, -27, -75, 88, 82, -23, -13, -38, 6, 65, 43, -63, -53, 49, 2, 34, 21, -1, -49, 
  -23, 102, 23, 84, -25, 73, 95, -103, 118, -20, -48, 92, 63, -3, -100, 39, 92, -18, 16, 85, 
  83, 22, 71, 3, 103, 36, -100, 0, -41, 4, 86, 24, 5, -119, -4, 84, -90, 83, -38, -31, 
  56, -93, 6, -25, 86, 92, -31, 17, 42, -71, -34, 44, -61, -74, 77, -1, -19, 100, 17, 52, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0046464437618851662, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 318, 338, 384, 1051, 886, 260, 238, -7, 175, -21, 92, 1090, 273, 320, 249, 462, 377, 645, -83, -12, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00011271255789324641, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*189] = { 
  -17, -48, -35, 59, 10, 59, 55, -4, 65, -12, 16, 73, -23, -4, 38, 100, 10, 28, -41, -20, 83, -30, 89, -14, -63, 5, -78, -18, -36, -63, 31, 34, 13, -65, -48, 12, -88, 3, 5, -79, 0, -45, -50, -27, -96, 39, 17, 73, -46, -8, 44, -44, 39, -32, -82, 1, 62, 28, 79, 9, 94, -5, 13, -58, -89, -55, -18, 11, 26, -29, 1, -75, -39, -4, 1, -7, 27, 42, -3, 69, 16, -17, -4, 33, -15, -9, -83, -28, -46, -35, 25, -3, -20, 76, 6, -82, 60, 50, -61, -34, -23, -52, 5, 0, -27, -31, -2, 26, -22, 1, 71, 13, -14, 35, -83, 26, -52, 31, -41, 38, 51, 32, 20, 70, -46, -4, 43, -27, 40, 4, -23, -7, 70, 24, 73, -32, 18, 87, -35, 57, 43, 19, -17, -29, -43, -19, -23, 7, -23, -3, -7, 29, 25, 84, -5, -28, 60, 6, -46, 13, 76, 106, 9, -12, -9, -48, -69, -49, 28, 51, -48, -48, -25, -7, -11, 15, 32, 15, -77, -57, -14, 17, -35, -37, 53, 6, -53, -102, -20, 
  -68, 60, 40, -10, -38, 8, 39, 5, -10, 52, -50, -4, -10, -17, 5, -61, 38, 36, 59, -53, -62, -19, 42, -8, -13, 17, 31, 37, -29, -38, -16, 34, 63, 50, 16, 5, -21, 25, 2, -7, -36, -35, 47, 73, 68, 5, 59, -46, 3, -30, -93, 0, 5, -25, -15, -56, -84, 36, 38, -38, -59, 45, -38, -19, 47, 54, 41, -95, 63, -8, 60, -33, 41, -21, -16, 19, -14, -60, -11, 34, -34, -59, -37, -9, 31, -1, -2, -45, 6, -52, 11, 8, 38, -4, -7, 67, -30, -76, 15, -63, 21, 50, -3, 10, -60, 49, 32, -60, -47, -40, -37, -55, 68, 16, 2, 80, 35, -11, -74, -65, 7, -91, -34, -47, 24, -16, -12, 37, -22, 82, -30, -16, 45, 12, 99, 76, -12, -41, 5, 45, -52, 16, -44, -24, -7, 50, 58, 38, -51, -88, -44, 8, -61, -81, -15, 50, 23, 46, -61, -35, -86, -104, -15, -50, -87, -27, -26, -5, -45, -28, -18, -50, 26, -65, -26, 89, 16, -37, -38, -70, -41, 10, 6, -5, -55, 82, -15, 14, 91, 
  31, -45, -91, -26, 48, -30, 36, 47, 46, -24, -64, -11, -57, 33, -40, 35, 13, 34, -19, 15, 60, -86, 26, -62, 9, -29, 31, 36, -43, -57, -32, 43, 25, -72, -16, -11, -65, -13, 49, -63, 32, 22, -63, -15, 16, -30, -45, -60, 20, -15, 26, -8, -21, -11, 40, -76, -7, 9, -2, -33, 50, -46, -29, 5, -72, -30, 37, -10, -58, -49, -10, -88, -5, 51, -1, -29, -77, 35, -30, -35, 35, -60, 30, -2, 9, 8, -31, -28, -75, -4, -56, 39, 12, -33, 46, 29, 1, 21, 3, 7, -87, -63, -54, -76, 27, -38, 51, 45, -5, -17, -31, 34, 3, -62, -64, -75, 24, 73, -1, 32, -35, 69, 70, -73, 64, 58, 8, 7, -108, -8, 45, -53, 2, 18, 16, 21, -38, 57, 45, 24, -18, 53, 69, 47, -61, 0, -49, 16, -4, 18, 16, -42, -25, 5, -1, 66, 34, -38, 48, -66, 8, 61, 11, 71, 2, -40, -50, -12, -43, -15, -47, -14, 4, -53, -20, 10, 46, -23, -32, -41, 58, -65, 5, 57, -20, -10, 34, -22, 13, 
  -64, 35, -106, 47, 11, 36, 28, 98, 60, -76, 56, 56, 49, 8, 22, -18, -42, 2, 26, 40, -52, 29, -27, -15, 56, 68, -4, 72, 81, 58, 7, 59, 101, -18, 39, 33, 101, -23, 34, 80, -29, 71, 14, 69, 76, -55, -22, -62, 37, 47, -30, 16, -7, -73, 17, -29, -61, -59, -29, 5, 56, 17, 72, 43, -68, -112, 85, -13, -25, -37, 74, -16, -20, -69, -24, 11, -8, 51, 21, 68, 13, 32, 45, -25, -13, -62, -14, -39, 18, -57, 13, 16, -61, -9, 41, -6, -33, -12, 69, -3, -11, -9, 60, -19, -30, 4, 1, -30, -3, 9, -73, 27, 4, 42, 2, 55, -44, 21, 33, -19, -87, 40, 7, 24, -38, 1, -20, -67, -30, 41, -7, -75, -30, 61, -15, -38, -32, 3, 35, 55, 34, 31, 0, -28, 4, 29, -15, -25, -30, -70, -17, -21, 39, 33, -48, 5, 22, 66, -42, -73, -55, 7, 21, 31, -51, 10, -16, -56, 39, 19, -59, -31, 11, -64, 35, 56, 22, 29, 39, -93, -15, 43, 51, 28, -17, -65, -15, 67, 37, 
  13, -9, 0, -27, -40, -63, 64, 14, 18, 44, -40, 23, -36, 10, -25, 47, 62, 30, -51, -50, -19, 18, -39, -52, -35, -31, 1, 58, -71, -77, 16, -40, 21, -74, -35, -74, -66, -105, 22, 7, -34, -12, -54, -23, 21, -37, 95, 53, -6, 73, 74, 23, -91, -59, -64, 22, 57, 13, 23, 20, -7, -57, 48, 42, -79, 28, -26, 70, -61, 8, -48, 40, 71, 54, 56, 58, -28, -9, -25, -6, 78, -73, 40, -34, 26, -64, 7, -57, 46, -6, -43, 8, 25, 61, 38, -14, 17, 9, -57, -64, -42, -64, 18, -48, 46, -39, -46, -6, -35, 48, -26, -30, -69, -18, -29, -53, -54, -38, -17, -6, 79, 9, -36, -7, -31, 23, 31, -112, -62, 49, 25, -23, 13, -48, -54, -51, -21, 1, -109, 41, 11, -20, 42, -15, 29, -90, 27, -35, -66, -58, -8, -4, 9, -4, 23, 44, 46, -26, 55, -66, 2, 69, -32, -23, -52, -69, -13, -35, 29, -34, -38, -98, -86, 33, 26, -39, -44, 11, -43, -3, -77, -23, 24, 36, 31, -68, -53, -73, 2, 
  -13, 65, 27, -4, -24, -40, 13, 77, -26, 28, -48, -6, -59, 43, 30, 17, -61, 12, -22, 14, -40, -38, -2, -32, 52, -21, 12, -18, -26, 70, -18, -15, 49, -29, 31, -59, 46, -37, 30, 56, 47, 26, -40, -18, 13, -57, -46, -40, -8, 35, 59, -4, 31, -17, 37, 50, 36, 2, 47, 17, 27, -56, 49, -48, -9, 21, -38, 41, 75, 34, 60, -36, 40, -41, -58, -68, -5, -7, 34, -21, -68, 31, -28, 49, -1, -38, 41, 10, 88, 2, 26, 25, -26, 71, 16, 2, -5, 30, 6, 52, 7, 39, 70, -25, 35, 28, 78, -26, 45, 53, 5, 12, 36, 52, 66, 42, 45, -54, 28, -44, -69, 27, -64, 10, -12, 54, -4, -21, -14, -58, 3, 30, -33, -12, 26, 73, 41, -40, 56, 61, 52, 13, 17, -22, 17, -29, 70, 69, 66, -20, 64, 26, 21, -62, 50, 4, -13, 59, -16, 9, 53, -59, 43, -54, 55, -59, 70, -28, 45, 8, -2, 60, -51, 4, -54, 15, -54, -20, 66, 45, 65, 31, -54, -42, -5, -32, 7, -40, 54, 
  22, 10, -21, -40, -31, -81, -40, 13, -57, -26, -21, -32, -23, 17, -2, -41, -48, -57, 55, 28, -65, -7, -54, 36, -46, -10, 83, -69, 50, 24, 39, -86, -4, 0, -74, 34, -54, 37, -58, 81, 5, 15, -24, 0, -26, -59, 42, -48, -2, -41, -67, 40, -68, 45, 24, -7, -21, 49, 20, -51, -76, -11, 19, -50, 97, 53, -53, 32, -22, -17, 31, 84, -14, 25, 5, 25, 42, 44, 22, -48, 43, 53, -3, 8, -44, -32, 56, 18, -43, -68, -59, 35, -48, 44, -31, -44, -27, -61, -62, -1, -30, -49, 0, 7, 77, 4, -20, -49, -53, -20, -17, 50, 57, -66, 45, 0, 57, -45, -69, -40, -39, 3, -50, 9, -32, -47, -16, 99, 12, -50, 15, -62, -6, 30, 54, 57, -45, 30, 48, 53, 6, 25, -46, -71, -38, 10, 42, -61, 16, -1, -84, 40, -17, 17, -41, -68, -18, -51, 18, -50, 38, -10, -43, -56, 21, -31, -24, 20, 45, 9, -79, 40, 35, 46, 22, -41, -90, -29, 26, 0, 60, -19, 43, -8, -49, -52, 40, -38, -15, 
  47, -83, 39, 41, 37, 32, 25, 45, 5, 73, -7, 90, -6, 57, -21, -55, -19, -36, -48, 65, 65, -32, -26, -2, -14, 67, -26, 28, -55, -18, 27, 72, 11, -56, -18, -72, -23, 9, 42, -35, -20, 20, 82, 80, 25, -4, 36, -50, -34, 39, -37, -27, -17, -3, -22, -48, -52, 53, 44, -54, -19, -8, 50, -58, -21, 62, -11, -46, -59, 50, -63, -1, -23, 39, -1, 6, -43, 35, -43, 51, 72, -72, 27, -2, -4, -78, 18, 23, 66, 0, -17, -53, 23, -23, -39, -66, -22, -38, -11, 59, -44, 35, -5, -89, -30, -36, -32, -47, 81, 4, -13, -79, -15, 14, 16, -54, 28, 0, -23, 20, -21, 10, -21, -52, 33, 23, -48, -71, -24, -13, 52, -6, 5, -3, -77, 19, -44, -34, -14, -9, -15, 35, 53, 44, 11, 13, -19, -64, 35, 25, 41, -43, 21, 52, 36, 12, -40, 17, -5, -13, 17, -48, 34, -14, -9, -29, -80, 28, -72, -22, 28, -41, -40, 10, -61, 9, -32, -67, -44, -16, -33, 44, -17, -29, -44, -3, 24, 26, 34, 
  33, 77, 3, 5, -36, 27, -34, -63, -27, -30, -4, 16, 15, -53, -9, -50, 17, -33, 73, 11, 46, 30, 47, 32, 45, 43, 47, -11, 47, -58, 37, -75, -5, -10, -69, -21, -50, 73, -54, 12, -30, -36, -72, -31, -58, 11, -41, -24, -42, 11, -83, -69, 62, -54, 24, 32, 0, 27, -8, -34, 17, -35, 38, -15, 42, -127, 94, 83, 61, -27, -6, -7, 28, -34, -24, -42, -34, -24, -21, 66, -15, -33, -49, -46, 78, 37, -8, 6, 18, 30, -2, -61, -66, -22, 41, 22, 75, 16, 36, -32, -50, -59, -46, 43, 25, 56, -18, -6, 11, -22, -26, 64, 36, 39, 79, 74, 40, -37, 67, -10, 53, 52, 19, -11, 39, -35, 5, 59, -82, 47, -74, 32, -85, -26, -61, -9, -51, 48, 24, 26, 44, -22, 27, -43, -52, 7, 35, -36, -51, -44, 55, 46, -45, -53, -32, 41, -73, -72, 30, -19, 21, -10, -5, -56, -30, -61, -58, 18, 23, 27, 62, 4, 14, 48, 57, -8, 55, -14, -59, 25, -40, -18, -45, -22, -6, 26, -50, -10, -23, 
  -52, 60, -37, -13, -48, 44, -58, 4, -35, -61, -51, -43, -68, -10, -35, 58, -4, 46, 57, -35, -7, 49, 18, 68, 72, 50, 8, 23, 4, 38, -25, -13, -44, 6, 57, 27, 51, 55, -2, 18, 20, 33, -28, 24, -24, -63, 53, 38, 67, -48, 38, 64, -65, -59, -34, 17, 46, 16, -53, 26, -53, -27, -38, 53, -3, 0, -83, -37, -41, 26, -65, 32, 41, -12, 1, -57, 58, -16, -88, 25, 14, 51, -63, -35, -46, 51, -42, -17, 50, 31, 57, 36, -4, 9, 18, 50, 14, -40, -60, -29, 36, -37, -42, -31, 7, -11, -64, -24, 33, 39, 49, -29, -29, -27, 80, 60, 47, 30, 46, 39, 52, -70, -53, 48, -58, 11, 56, -15, -5, 12, -41, -34, -19, -11, -55, 36, 65, 6, 16, -65, 58, -44, 29, 3, 13, 30, 68, -2, -71, 0, -58, -59, -27, -41, 67, -47, -45, 36, -51, -1, -3, -60, 39, 30, 13, -56, -20, -28, -3, -35, 17, 53, 52, -12, -55, -43, 7, -44, 52, -5, -62, 3, 44, 60, 40, -40, 73, 52, -15, 
  69, 37, 64, -83, -73, -20, 40, 8, -10, 34, -39, 32, 23, -40, 45, -27, 2, 0, 28, 23, -50, 40, -63, 55, 57, -15, -37, -26, 49, 45, -69, -56, -58, -8, 77, 61, -23, -61, -49, 12, 19, -11, 12, -16, -19, 60, 16, -52, 45, 23, -19, -36, -8, 3, 49, 61, -35, -18, 30, 1, 30, 37, 57, 46, 31, -41, -80, 11, 32, 7, 33, -13, -30, -27, 13, 43, 9, -40, 22, 50, -40, -41, 24, -45, -16, 68, 1, 33, 0, -9, 16, 75, 39, -14, -4, 11, -29, 30, -59, 30, 62, 44, 29, 25, 25, -22, -2, -50, 65, 9, -6, -7, 28, 42, -52, 31, -31, 47, -16, -35, -40, -75, -57, -65, 38, 12, -41, 10, 60, -71, 30, -15, -39, -54, 34, 35, 2, -51, 67, 43, -17, -37, -14, 29, 0, -52, -3, -24, 24, -21, 6, 39, 40, 67, -26, -23, -17, 17, 3, 18, 71, -49, 67, 35, 7, 16, 19, -33, 7, 10, 52, -17, -28, -54, 53, 53, 23, 10, 29, 69, 24, -54, 36, -46, -9, 44, -52, 36, 58, 
  -3, 28, 60, -35, -63, -40, 99, 7, 77, -5, 88, 102, 74, 79, 4, 62, -8, -9, 80, 23, 16, 11, 91, 29, 49, 56, 65, 61, 97, 51, 13, -5, 24, -7, 39, -7, -27, 46, 37, 54, 57, 75, 67, -7, -25, -4, 29, 48, -38, 13, -34, 67, 33, 40, 77, 57, 55, 1, 20, -40, 66, 48, 9, -19, 37, 32, 56, -5, 9, 2, -41, 4, -36, -23, 77, 9, 44, 62, 35, 23, 39, 64, -54, -42, -54, -49, -31, 44, 1, 45, 40, -36, -52, -38, 29, 29, 40, 56, -17, -8, 6, 10, 53, 60, 62, 32, 13, 78, 13, -55, -3, 38, 36, 18, -55, -25, -53, 7, 53, 24, 63, 68, 2, -10, -7, -15, -38, -56, 47, 73, -15, 45, 33, -7, -54, 21, -33, 69, -26, 43, 5, 15, 4, 48, 49, -52, 12, -23, -37, -27, 51, -31, -12, 12, 0, 35, 43, 80, 9, 3, 85, -2, 26, 47, -44, 47, -10, -30, 60, 31, 36, 17, 70, -11, 70, 7, 72, 78, 2, 79, -2, 75, 54, 66, -32, 41, 18, 51, 84, 
  -36, -101, -18, -4, 63, -75, -60, -89, -78, 15, -26, -85, 3, 17, -43, 35, 8, -27, 56, -26, 16, 29, -56, 44, 36, -23, 11, -45, 43, -15, -45, 0, -66, 57, 35, 41, 67, -39, -68, -38, 0, 12, -64, -39, -57, -29, 45, 31, -4, 58, 31, -54, -66, 22, -37, -64, -58, 20, -14, 24, -48, -66, -72, 49, 47, -45, 81, 61, 24, 56, 29, -23, 29, 50, 33, -46, -13, 54, -52, -44, 29, 39, 63, 26, 72, 88, -69, -58, -32, 14, -71, 40, -13, -21, -75, -42, 33, 1, 57, -6, -34, 34, 29, 48, 43, -60, -1, 32, 9, -23, -15, 15, 37, -10, 5, 26, -21, -23, 50, 47, 52, -5, 54, -23, -7, 47, -74, 50, -35, 36, -33, 19, 40, -16, 8, 48, 35, -1, 60, 49, 34, 5, 46, -12, -7, -15, -56, 80, 3, -53, 10, -35, -13, 12, 4, 75, -39, 35, -35, -40, 30, -34, -87, -27, -48, -51, 11, 73, -19, -14, 78, -14, -50, 27, 32, 68, -15, 26, -7, -46, -27, -12, -25, -11, 51, -50, -36, -37, -2, 
  29, -27, -56, -40, 25, 58, -29, 78, 10, -23, 11, 42, 68, -18, 18, -41, -56, 3, -56, -27, -49, -40, 28, -4, -42, -29, 12, 106, 29, 22, 59, -37, -22, -34, -21, 70, 77, 38, 73, 9, 97, 74, 49, -59, 49, 1, 13, 30, 92, 46, 17, -25, -81, -44, 64, 13, -2, 37, -1, -47, -42, -22, -11, -44, 41, 63, 88, 81, 32, 85, -14, 20, 48, -7, 38, -67, -21, -44, 29, -37, -20, 39, -30, -24, 44, -10, 62, 79, -14, -100, -9, 0, -69, 14, -63, -17, -12, 61, 12, -26, 31, 35, 15, -32, -70, 41, -23, -32, -44, 16, 18, -65, -45, 6, -24, 61, 55, -27, 25, -75, -19, -56, -35, -38, 56, -21, -66, 54, 8, 80, -59, -54, 10, 14, -29, -58, 55, -5, 14, 110, 65, -1, 19, -63, -7, 62, 24, -22, 3, 9, -34, -22, -25, -51, 35, 68, -34, -9, 25, -47, -66, -4, -3, 29, -8, 7, 74, -79, -55, -50, 55, -46, 16, -6, -9, -21, 17, 62, 3, 11, 44, -29, -45, 4, -6, 48, -76, 27, 117, 
  66, -26, -14, 12, 3, -29, -17, 36, 44, 34, 70, -53, -55, 70, -54, -7, -56, 13, 45, -49, 72, 79, -33, 40, -57, -35, -11, -54, 66, -13, 84, -26, -24, 51, 1, -38, -62, 6, 58, -66, -69, 54, -60, 43, -27, 35, -31, -50, -80, -29, -10, 29, 23, -10, -51, -47, 56, -16, 66, -33, 20, 35, -28, 60, -1, 93, 34, 19, -7, 49, -20, -57, 86, -15, 44, 27, -13, 29, 0, 3, 24, 24, -41, -21, 10, -45, 64, 10, -31, 35, -4, 52, 12, 67, -53, -19, 42, 63, 60, 57, -59, 78, -51, 54, -70, -35, 37, -41, -5, -26, -36, -31, 51, 28, -91, 43, 72, -54, 37, 50, -58, -17, -35, -59, -59, -89, -1, 49, 103, -52, -23, -32, -11, 3, 64, 46, 70, 33, -68, 64, -32, 37, -17, -22, 47, 57, 29, -37, 35, 58, -7, -50, 56, 37, 14, -34, -14, 37, -9, -47, 40, 55, 25, 8, -45, -24, 34, 25, 63, -28, 53, 38, -22, -24, -45, 37, 67, 37, 10, 40, -63, -38, -46, 0, 25, 30, 19, 13, 37, 
  -4, 34, -78, -47, -42, 6, -8, 18, 29, 15, -12, 26, -36, 30, 27, 50, 21, 38, 25, 38, -64, 55, -53, 33, 20, 1, -27, -26, -14, -34, 16, -20, -23, 34, -11, 9, 0, -66, 17, 61, 42, -32, 14, -55, 46, -44, -67, -22, -50, 47, 30, -8, 44, 55, 21, -44, 55, 22, -57, 52, -4, -47, 1, -35, -14, 4, 31, -18, 13, 54, -39, 69, 57, 61, 21, 60, -30, 11, 56, 33, -41, -43, 5, 61, 68, 47, 5, 27, 26, 61, -15, 57, 5, 30, 52, 41, -59, 32, 33, 32, 46, 58, 63, -23, 44, -52, 6, 20, 57, -39, 20, -46, -67, 12, 38, -49, -15, -51, 3, -8, -34, 12, -4, -27, 35, -17, -51, -46, -59, -28, 21, -33, 4, 47, -57, -41, -49, -27, 3, 3, -45, 9, -37, -19, 43, -2, 56, 3, -8, -60, 21, -37, -38, 45, 32, 18, -41, 44, -44, -68, -49, 53, -64, 33, -4, -31, -72, 35, 30, -2, -22, -41, -48, -50, 29, 63, -8, -70, -64, -22, 56, -41, -56, -49, -25, 1, -19, -34, -9, 
  -4, -74, -52, 17, 80, -30, -33, -69, 6, -75, -66, -39, 6, 19, -46, 10, -55, -36, 31, -26, -69, -44, 17, -28, 32, -25, -9, 41, -63, 55, 12, -11, 55, -46, -31, -43, 22, -56, -35, 5, 4, -13, -3, 37, -8, -63, 29, -79, -5, -37, -5, -6, -9, -41, -13, -71, -28, -23, 40, -58, -71, 46, -49, 0, -2, -26, 29, 1, 18, 85, -53, -16, -41, 48, 55, 50, -23, 13, -33, 5, 14, 63, -72, -40, -6, 82, 9, -49, 32, -32, -8, 53, 42, -21, -17, -24, 4, -42, 68, -29, -8, -25, -23, 14, 93, 51, 30, 47, -37, -65, 36, 55, 78, -54, -26, 33, -13, 49, -51, -44, 47, 5, -4, -4, 73, 45, -18, -41, 47, 51, -29, 41, -28, -6, -60, -13, 39, -52, 57, -80, 37, -30, 25, -42, -32, 17, 61, 41, 5, 3, -55, -14, 30, 17, -7, -32, 29, 49, -65, -35, -87, 8, -34, 45, 41, -35, 54, -70, -14, 21, 40, 3, 30, 48, 28, -9, 26, 42, -57, 69, 59, -40, -78, 16, 52, -41, -50, 48, -42, 
  -12, 34, 93, 44, 46, -3, 1, 75, 21, 0, -26, 82, -28, 56, -39, -3, -56, 1, 65, -40, 37, -24, -46, 57, -42, -60, -29, 14, 3, -17, 6, -44, 5, 38, 15, 67, 61, -59, 50, -63, -59, -22, 66, -26, 4, -35, 24, 80, -57, 29, -16, -15, 68, 49, 24, -45, 53, -65, 1, -16, 52, -34, 48, 72, 4, 76, -27, -19, 66, 33, 67, -24, 44, 73, 52, 6, -29, -20, 59, -65, -68, -40, -45, 34, 36, 73, 1, 42, 50, 49, 25, 90, -32, -2, 81, 60, 53, -9, 91, -49, 85, 55, 26, -21, -39, -51, -45, 86, 40, -48, -50, -23, 59, 8, -46, 51, 70, 77, -31, 13, -25, 81, 26, 86, 23, 31, 33, 63, 102, 35, 7, 41, -51, 53, 28, 1, 75, 59, -4, 1, -55, -38, -60, 70, 38, 9, 20, 16, 44, -6, 34, 52, -75, -73, -7, -29, -18, 19, 33, -21, -34, -51, -49, -8, 62, 59, -42, -24, 65, -4, -63, -20, 38, 66, 55, 55, 18, -9, -34, 48, 73, 74, 68, -28, -45, 51, 81, -8, -14, 
  -56, 1, 60, -73, 24, 7, -42, -2, -6, -23, -57, -21, -59, -47, -47, -31, 6, -39, -33, 30, -29, 61, -35, 53, -27, -59, -4, -21, -57, -45, 34, -29, -43, -60, 68, 54, 14, -48, -54, -23, -50, 14, -40, 34, -3, -11, 66, 13, -57, -66, 2, -59, 28, -37, 44, -47, -41, -38, -12, 53, -17, -32, -40, 58, 45, -10, 33, -83, -6, 51, 20, 20, 54, -35, -61, 8, 61, 33, -9, 9, 21, 52, 88, 36, 71, 49, 89, 19, 23, -31, -39, 75, 58, -10, -57, -36, 49, 13, 63, -29, -42, 87, 18, 17, -13, 22, -24, -30, 14, 31, -56, 16, -52, -17, -11, -20, 63, 44, -60, -69, 50, -57, -34, 8, 0, 45, -12, -28, 26, 2, -70, -37, -6, -6, -7, -31, 16, 62, -26, 15, 46, -20, -12, -27, 61, 58, 18, 19, -21, -18, -5, 20, 45, 20, -12, -36, 29, -37, 64, -9, 22, -31, 17, -59, -29, -65, -36, 65, -7, 37, 53, -49, 65, 49, -15, 27, -48, -35, 39, 38, 26, -32, -61, 54, 47, -55, -66, -49, -24, 
  5, 100, 20, -69, -46, -10, 30, -10, 48, 46, -36, 63, 47, -2, 1, -17, 1, -58, -40, 21, -27, -58, 61, -43, -14, 3, -29, -18, 33, 62, -43, 12, 62, -31, 21, 43, -42, 25, 17, 1, -26, -35, 34, 52, 27, -20, -45, 44, 14, 13, 34, 38, -45, 41, 42, -14, 47, -46, -33, 66, -60, 51, -58, 25, -21, 40, -39, -75, -65, -65, -78, 14, -45, -47, -49, -8, -52, -85, -83, -69, 13, -7, 7, -48, 2, 23, 87, -2, 17, -14, -70, -7, -65, -33, 7, -42, -68, -83, 52, -47, -23, 34, 26, -37, -13, 61, -89, -71, -44, 15, 59, 55, -53, -50, 65, 29, -6, -56, -49, -5, 61, -28, 20, -49, 10, 12, -58, 2, -1, 14, -53, 0, 51, 69, 44, 83, 64, 59, -26, -26, 36, -8, 30, 39, 15, 57, -38, 63, -34, 5, -70, 49, -11, -42, 9, -56, -52, -8, -2, 42, -78, -76, 43, -6, 22, -42, 65, 43, 59, -51, -26, 33, 33, -23, 16, 62, -49, 4, -46, -9, 29, -48, -40, -30, -55, 26, -45, -14, -2, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,189 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0024714528117328882, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.054138932377099991, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.04733923077583313, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,2 } };
const TfArray<1, float> quant9_scale = { 1, { 0.11645318567752838, } };
const TfArray<1, int> quant9_zero = { 1, { 6 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 189, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 3780, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 192), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_928099_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_928099_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_928099_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_928099_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_928099_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
